apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops-tools
  labels:
    app: testomatic 
  name: testomatic 
spec:
  selector:
    matchLabels:
      app: testomatic 
  replicas: 1 
  template:
    metadata:
      labels:
        app: testomatic 
    spec:
      containers:
      - name: testomatic
        image: bakeryhead/my_public_repo:testomatic-amd64
        ports:
        - name: httpport
          containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: testomatic-service
  namespace: devops-tools
spec:
  selector:
    app: testomatic
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 32000
